In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("student_data.csv")

print("Dataset Shape:", df.shape)
display(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'student_data.csv'

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving student_data.csv to student_data.csv


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("student_data.csv")

print("Dataset Shape:", df.shape)
display(df.head())

Dataset Shape: (395, 33)


,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10


In [ ]:
# Numerical columns
df.select_dtypes(include='number').columns

Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2',
       'G3'],
      dtype='object')

In [ ]:
marks = df[['G1', 'G2', 'G3']].iloc[0].values

print("Student Marks Vector:")
print(marks)

Student Marks Vector:
[5 6 6]


In [ ]:
matrix = df[['G1', 'G2', 'G3']].head(5).values

print("Marks Matrix:")
print(matrix)

Marks Matrix:
[[ 5  6  6]
 [ 5  5  6]
 [ 7  8 10]
 [15 14 15]
 [ 6 10 10]]


In [ ]:
student1 = df[['G1', 'G2', 'G3']].iloc[0].values
student2 = df[['G1', 'G2', 'G3']].iloc[1].values

dot = np.dot(student1, student2)

print("Dot Product:", dot)

Dot Product: 91


In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)

print(result)

[[19 22]
 [43 50]]


In [ ]:
marks_data = df[['G1', 'G2', 'G3']]

covariance = np.cov(marks_data.T)

print("Covariance Matrix:")
print(covariance)

Covariance Matrix:
[[11.01705327 10.6388357  12.18768232]
 [10.6388357  14.1489173  15.59369659]
 [12.18768232 15.59369659 20.9896164 ]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(covariance)

print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[41.97661551  2.84406078  1.33491068]


In [ ]:
x = 5

derivative = 2 * x

print("Derivative:", derivative)

Derivative: 10


In [ ]:
x = 5
y = 20
w = 2

prediction = w * x

gradient = 2 * (prediction - y) * x

print("Prediction:", prediction)
print("Gradient:", gradient)

Prediction: 10
Gradient: -100


In [ ]:
x = 5

u = 3*x + 2

du_dx = 3
dy_du = 2*u

dy_dx = dy_du * du_dx

print("Chain Rule Result:", dy_dx)

Chain Rule Result: 102


In [ ]:
x = 5
y = 20
w = 2

prediction = w * x

error = prediction - y

gradient = 2 * error * x

learning_rate = 0.01

new_w = w - learning_rate * gradient

print("Old Weight:", w)
print("Gradient:", gradient)
print("New Weight:", new_w)

Old Weight: 2
Gradient: -100
New Weight: 3.0


In [ ]:
x = df['G2'].values
y = df['G3'].values

w = 1
b = 0

prediction = w * x + b

print("Actual G3:")
print(y[:10])

print("\nPredicted G3:")
print(prediction[:10])

Actual G3:
[ 6  6 10 15 10 15 11  6 19 15]

Predicted G3:
[ 6  5  8 14 10 15 12  5 18 15]


In [ ]:
loss = np.mean((prediction - y)**2)

print("Loss:", loss)

Loss: 4.030379746835443
